version: '3.7'

services:
  database:
    image: mysql:latest
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MS_PASSWORD_ROOT}
      - MYSQL_PASSWORD=${MS_PASSWORD}
      - MYSQL_DB=${MS_DATABASE}

  app:
    build: .
    command: npm run dev
    container_name: finance_control
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - .:/usr/app

volumes:
  mysql_data:
    driver: local
